### ISSUE TITLE
do not force to set setTitles() in a Builder

### ISSUE THREAD

**Issue by hardysim** [dvdciri/MultiChoiceRecyclerView#31]
> from https://github.com/dvdciri/MultiChoiceRecyclerView/issues/28#issuecomment-274800577

if needed I think the constructor would be a better place

**Comment by dvdciri** [comment]
Where am i forcing to set the title?

**Comment by hardysim** [comment]
The `MultiChoiceToolbar#Builder()` takes `setTitles()`.
If I **do not** add this to the builder, it crashes with:

```java
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
at com.davidecirillo.multichoicerecyclerview.MultiChoiceToolbar.<init>(MultiChoiceToolbar.java:26)
at com.davidecirillo.multichoicerecyclerview.MultiChoiceToolbar.<init>(MultiChoiceToolbar.java:9)
at com.davidecirillo.multichoicerecyclerview.MultiChoiceToolbar$Builder.build(MultiChoiceToolbar.java:122)
```

In my understanding, a builder is the thing where I *might* add options (but I *can* leave them unset).
Am I wrong?

---

This is not a bug - more like a architectural discussion ;-)

**Comment by dvdciri** [comment]
Correct, thanks for adding info, will fix this later
